# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.

# the subpath of your site, e.g. /blog
# This is to make fproxy work correctly
baseurl: "/USK@nrDOd1piehaN7z7s~~IYwH-2eK7gcQ9wAtPMxD8xPEs,y61pkcoRy-ccB7BHvLCzt3RUjeMILf8ox26NKvPZ-jk,AQACAAE/debbiesindex/25"

# This is the edition for the index.
indexedition: 24331

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

tag_page_layout: tag_page
tag_page_dir: tags
