# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.

# the subpath of your site, e.g. /blog
# This is to make fproxy work correctly
baseurl: "/USK@key/bcdef-doc/0"

# Site settings
title: Block Chain Defined to Enhance Freenet
email: debora_wpcke@t2ym4522mj5bndpph3wpxyqyyb77m6fo4byq64ac2pgmipzrhrfq.freemail
github_username: debbiedub
description: > # this means to ignore newlines until next property
  Documentation and development log of a block chain for freenet

# Time used in the site when exact time and timezone are not to be disclosed
# This is used as the end of an rfc822 time.
notime: "00:00:00 +0000"

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

tag_page_layout: tag_page
tag_page_dir: tags
