/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package freenet.bcdef;

import org.junit.Test;

import static org.junit.Assert.*;

import java.io.IOException;

public class AppTest {
    @Test public void pluginCanRun() throws IOException {
        // I need to mock a lot of the node to do tests on the plugin
	//    	App classUnderTest = new App();
	//        classUnderTest.runPlugin(null);
	//        classUnderTest.terminate();
    }
}
